# Generated by Django 3.1.5 on 2021-01-08 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('hashed_token', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tellonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('NEW', 'Nowy'), ('ACCEPTED', 'Pobrany'), ('DISCARDED', 'Odrzucony')], max_length=15)),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tellonym_api.user')),
            ],
        ),
    ]
