# Generated by Django 3.1.5 on 2021-01-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TellonymUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_username', models.CharField(max_length=64, unique=True)),
                ('hashed_token', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tellonym',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('NEW', 'Nowy'), ('ACCEPTED', 'Pobrany'), ('DISCARDED', 'Odrzucony')], default='NEW', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tellonym_api.tellonymuser')),
            ],
        ),
    ]
