# Generated by Django 3.1.5 on 2021-01-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellonym_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isStuff',
            field=models.BooleanField(default=False),
        ),
    ]
