# Generated by Django 3.1.5 on 2021-01-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellonym_api', '0002_user_isstuff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isStuff',
            new_name='is_stuff',
        ),
    ]
