# Generated by Django 3.1.5 on 2021-01-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellonym_api', '0003_auto_20210108_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
