# Generated by Django 3.1.5 on 2021-01-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellonym_api', '0004_auto_20210108_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
