# Generated by Django 3.1.5 on 2021-01-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellonym_api', '0008_auto_20210109_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellonym',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
