# Generated by Django 3.1.5 on 2021-01-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tellonym_api', '0009_auto_20210109_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashedToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TellonymUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_username', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='tellonym',
            name='nickname',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='hashedtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tellonym_api.tellonymuser'),
        ),
        migrations.AddField(
            model_name='tellonym',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tellonym_api.tellonymuser'),
            preserve_default=False,
        ),
    ]
