# Generated by Django 3.1.5 on 2021-01-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellonym_api', '0010_auto_20210109_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellonymuser',
            name='hashed_username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
