# Generated by Django 3.1.5 on 2021-01-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellonym_api', '0011_auto_20210109_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellonymuser',
            name='hashed_token',
            field=models.CharField(default='token', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HashedToken',
        ),
    ]
